### ISSUE TITLE
Source port randomization

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-os-example-client#113]
Looking at
https://github.com/ARMmbed/mbed-os-example-client/blob/master/simpleclient.h#L108
the random source port might be <1024 and thus selecting a registered port. Which might be no problem. At the same time randomly you might choose 5683 (or other locally used ports) by chance. Which might break things. OK, not in this application, but since it is a reference application it might make sense, to fix it here, before it spills in applications by others.

Please implement https://tools.ietf.org/html/rfc6056 with a check_suitable_port() function in this app.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1265

**Comment by jankii01** [comment]
Hi @markus-becker-tridonic-com ,

the easiest fix will actually be to change it so that it sets port = 0; 
that way we will use the pretty de-facto way of letting the network stack randomize the port.
However, it seems we'll have to get mbedOS 5.3 release in before we can do that.

**Comment by jankii01** [comment]
Hi @markus-becker-tridonic-com,

we have now merged this in: 

https://github.com/ARMmbed/mbed-os-example-client/commit/ece732d633323c8a2412770eba528f260433a93f

- please let me know, if you're OK with this?

**Comment by JanneKiiskila** [comment]
Closing out, internal randomizaitons now removed overall and we're using port(0) and letting the stack randomize it.
