### ISSUE TITLE
Thread SED configured with TCP fails

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-client#136]
Tested 5.3-rc3 (https://github.com/ARMmbed/mbed-os-example-client/tree/mbed-os-5.3-rc3)

Default option TCP fails. When changed to UDP works ok (device is registered in mDC).

Platform K64. Atmel RF.

[mbed_app.json.txt](https://github.com/ARMmbed/mbed-os-example-client/files/642975/mbed_app.json.txt)

```
Starting mbed Client example...
Using Mesh

Connecting to Mesh..
[DBG ][nsth]: connect()
[DBG ][evlp]: event_loop_thread
[DBG ][m6Thread]: PANID defa
[DBG ][m6Thread]: channel: 12
[DBG ][m6Thread]: channel page: 0
[DBG ][m6Thread]: channel mask: 134215680
[DBG ][m6Thread]: Mesh prefix: fd:00:0d:b8:00:00:00:00
[DBG ][m6Thread]: Master key: 00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd:ee:ff
[DBG ][m6Thread]: PSKc: 00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd:ee:ff
[DBG ][m6Thread]: PSKd: Secret password
[DBG ][ThSA]: service init interface 1, port 61631, options 0
[DBG ][ThSA]: service tasklet init
[DBG ][ThSA]: service init interface 1, port 49191, options 130
[DBG ][ThSA]: Service 2, Uri registration uri: c/tx
[DBG ][ThSA]: Service 2, Uri registration uri: c/mg
[DBG ][ThSA]: Service 2, Uri registration uri: c/ag
[DBG ][ThSA]: Service 2, Uri registration uri: c/pg
[DBG ][ThSA]: Service 2, Uri registration uri: c/cg
[DBG ][ThSA]: Service 2, Uri registration uri: c/as
[DBG ][ThSA]: Service 2, Uri registration uri: c/ps
[DBG ][ThSA]: Service 2, Uri registration uri: c/cs
[DBG ][ThSA]: Service 2, Uri registration uri: c/cp
[DBG ][ThSA]: Service 2, Uri registration uri: c/ca
[DBG ][ThSA]: service init interface 1, port 61631, options 0
[DBG ][ThSA]: Service 3, Uri registration uri: c/mg
[DBG ][ThSA]: Service 3, Uri registration uri: c/ag
[DBG ][ThSA]: Service 3, Uri registration uri: c/pg
[DBG ][ThSA]: Service 3, Uri registration uri: c/cg
[DBG ][ThSA]: Service 3, Uri registration uri: c/pq
[DBG ][ThSA]: Service 3, Uri registration uri: c/es
[DBG ][ThSA]: Service 3, Uri registration uri: c/ab
[DBG ][ThSA]: service init interface 1, port 61631, options 0
[DBG ][ThSA]: Service 4, Uri registration uri: d/dg
[DBG ][ThSA]: Service 4, Uri registration uri: d/dr
[DBG ][ThSA]: Service 4, Uri registration uri: d/dq
[DBG ][ThSA]: service init interface 1, port 61631, options 0
[INFO][m6Thread]: Start Thread bootstrap (SED mode)
[DBG ][ThSA]: service tasklet initialised
[DBG ][nnvm]: ns_nvm_data_read() key=com.arm.nanostack.thread.static_link_cfg, l                                                                                                             en=120, ctx=0x2000b1c4
[DBG ][rnvm]: platform_nvm_read() com.arm.nanostack.thread.static_link_cfg len=1                                                                                                             20

Connection to Network Failed -3010! Exiting application....
```

@jankii01

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1303

**Comment by jankii01** [comment]
True, mesh only supports UDP.

**Comment by jankii01** [comment]
Please see this for example; https://github.com/ARMmbed/mbed-os-example-client/pull/124

**Comment by jankii01** [comment]
This fixes it: https://github.com/ARMmbed/mbed-os-example-client/pull/139

**Comment by jankii01** [comment]
@MarceloSalazar - please confirm the fix.

**Comment by MarceloSalazar** [comment]
@jankii01 thanks for the fix. I'm going to test this tomorrow asap.

In the meantime, could you have a look to the markdown doc?

- IP address setup (https://github.com/ARMmbed/mbed-os-example-client#ip-address-setup)
Ethernet now supports IPv4 and IPv6. How to select this is unknown.

- Changing socket type (https://github.com/ARMmbed/mbed-os-example-client#changing-socket-type)
Need to explain whether a network interface supports UDP, TCP or both. Something like this would help (need to double check whether is correct):

| Network  interface                    | UDP   | TCP | 
| ------------------------------|:-----:|:-----:|
| Ethernet (IPv4)               |   X   |   X   | 
| Ethernet (IPv6)               |   X   |       | 
| Wifi (IPv4)                   |   X   |   X   |
| Wifi (IPv6) - Not supported (?)  |       |       |
| 6LoWPAN/Thread (IPv6)         |   X   |       |

**Comment by MarceloSalazar** [comment]
I confirm the original issue is fixed:

Tested latest commit (https://github.com/ARMmbed/mbed-os-example-client/commit/8ce84b520ae0da685bf800addd4dcfc8401acc58) on mbed-OS-5.3 branch.

K64, GCC_ARM, mbed GW
Device successfully registered in mDC.
