### ISSUE TITLE
Fail building with uvision5

### ISSUE THREAD

**Issue by SYuPing** [ARMmbed/mbed-os-example-client#141]
Hi, 

I want to use Keil to build this project, and I command "mbed export -i uvision5" on mbed-cli, 
Then I open the file which was exported and try to build, but the error shows:

Error: *** Project 'mbed-os-example-client-master', Target 'mbed-os-example-client-master', Device 'Freescale::MK64FN1M0xxx12' is not supported by Toolchain ! ***.
Build Time Elapsed:  00:00:00

How to solve this?
the toolchain which I used is gcc not ARMCC, is this reason caused?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1304

**Comment by SeppoTakalo** [comment]
Use Keil pack installer to install the support packages for these boards.

![screen shot 2016-12-12 at 14 57 51](https://cloud.githubusercontent.com/assets/3104794/21100195/6b98da84-c07b-11e6-900e-294cce851d8c.png)

For me, its in `C:\Keil_V4\UV4\PackInstaller.exe`

Search for `K64F`
On the right panel, install required packs.

**Comment by SYuPing** [comment]
OK, I could build project after I installed required packs.
Thanks a lot.

Close this issue
