### ISSUE TITLE
OOB - Missing instructions on enabling Ethernet IPv6

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-client#146]
Please add info to the docs asap - branch mbed-os-5.3

@jankii01 @0xc0170 @adbridge

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1305

**Comment by MarceloSalazar** [comment]
Instructions have been added here:
https://github.com/ARMmbed/mbed-os-example-client/commit/a9a3580ff91ad6ba5afaed47e2bd8ab13012aca7
