### ISSUE TITLE
Gateway role

### ISSUE THREAD

**Issue by finikorg** [ARMmbed/mbed-os-example-client#187]
Can I use frdm-k64f + 802.15.4 shield as a gateway? It has almost the same hardware as a 6lowpan gateway from Firefly, right?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1518

**Comment by yogpan01** [comment]
@SeppoTakalo Can you please answer this query ?

**Comment by SeppoTakalo** [comment]
Yes.
The example application is currently here: https://github.com/ARMmbed/k64f-border-router

It uses K64F and Atmel RF shield.
In future, the repository will move and more boards will be supported.

**Comment by finikorg** [comment]
@SeppoTakalo There is a note there "Note: This Border Router does not support Thread."

**Comment by SeppoTakalo** [comment]
For mbed OS 5.4 release, we will also publish Thread mesh networking support.

Current one is just in 6LoWPAN-ND mode.

**Comment by SeppoTakalo** [comment]
I'll close this issue as the question is answered.
For follow up questions you can still use this ticket, thanks.
