### ISSUE TITLE
WIFI_ODIN configuration and .mbedignore instructions

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-os-example-client#195]
The instructions to add the `.mbedignore` file for the conflict between LWIP and the mesh RF stacks are at the very bottom of the README. I missed these for the first 10 minutes I was trying to use the WIFI_ODIN configuration.

Perhaps we could break down the steps by the `"network-interface"` setting in the mbed_app.json? And perhaps reference the users to the already available config files in the `/config` folder?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1528

**Comment by yogpan01** [comment]
@peknis01 Can you check the documentation bit ?

**Comment by bridadan** [comment]
To be clear, most of the information is already in the README. But with a little reorganization I think the experience could be much smoother!

As a user, my thought process is "look for instructions for my configuration -> read those instructions" vs "read most instructions and then search around a bit more if things aren't working". 

Thanks again @yogpan01 @peknis01!

**Comment by peknis01** [comment]
Take a look at: https://github.com/ARMmbed/mbed-os-example-client/pull/197

**Comment by yogpan01** [comment]
This can be closed as we have now updated the README documentation structure.
