### ISSUE TITLE
[OoB_5.4.1] [NuMAKER_PFM_NUC472 + AT233 shield + Thread BR] : Pinmap not found.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/mbed-os-example-client#208]
Steps to reproduce:
1. import example, switch to OoB branch, update FW on BR with ThreadDynamic.bin from https://github.com/ARMmbed/mbed-os-example-client/tree/oob-test-mbed-os-5.4.1 . Make sure BR is up & running.
2. mbed compile -t ARM -m NUMAKER_PFM_NUC472 --app-config configs\mesh_thread.json
3. If compile errors regarding AtmelRFPhy.c, copy the "mesh-mbedignore" from configs directory.
4. Flash target with binary.

Result on serial terminal:

![pinmap_not_found](https://cloud.githubusercontent.com/assets/17567812/23910389/78ceaa3c-08d1-11e7-88bf-cef5d6fb31a9.JPG)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1565

**Comment by teetak01** [comment]
@ashok-rao could you please open an issue to mbed-OS. This not an application issue.

**Comment by ashok-rao** [comment]
@SeppoTakalo .. any instructions on how to add support for this target? Maybe something to include in the docs for other users / other platforms too ?

**Comment by 0xc0170** [comment]
> @ashok-rao could you please open an issue to mbed-OS. This not an application issue.

+1. It would be helpful to provide what pins are used in this application (or better to pinpoint which pins fails). This board might not be compatible with the shield requirements. 
@ashok-rao  Please provide some additional information that would help us to resolve this .

**Comment by JanneKiiskila** [comment]
Hi,

@ashok-rao , @0xc0170 , @bulislaw  - any new updates on this case? I moved our JIRA ticket to IOTMORF, as this is not a client issue (unless you give us some instructions how to add something our documentation, but that info anyway needs to come from You first).

Best Regards,


Janne

**Comment by 0xc0170** [comment]
@ccli8 @cyliangtw Can you have a look at this issue with the pinmap?

**Comment by cyliangtw** [comment]
In `mbed_app.json`, it needs to define macros for AtmelRF shield board as:
```
    "macros": 
        ["ATMEL_SPI_MOSI=A2", "ATMEL_SPI_MISO=A1", "ATMEL_SPI_SCLK=A4", "ATMEL_SPI_CS=A3", "ATMEL_SPI_RST=D5", "ATMEL_SPI_SLP=D7", "ATMEL_SPI_IRQ =D9", "ATMEL_I2C_SDA=D14", "ATMEL_I2C_SCL=D15"],    
```

**Comment by JanneKiiskila** [comment]
Does the information from @cyliangtw  resolve this issue @ashok-rao ?

**Comment by teetak01** [comment]
That does not look like a very permanent solution. That configuration should go to inside mbed OS, not to application mbed_app.json.

**Comment by cyliangtw** [comment]
NUC472 board pinout is Arduino R1 type and not got any specific pinout requirement in mbed enable validation criteria. So, NUC472 board SPI pins are different from current Arduino R3 type. 
About Atmel RF driver, it's default ATMEL_SPI_xxx are Arduino R3 type. As a result, we resolve it by mbed_app.json .
Anyway, our future boards will follow R3 type.

**Comment by teetak01** [comment]
Closing.
