### ISSUE TITLE
[NUCLEO_L476RG] Unable to connect when using Wifi (ESP8266) + TCP (default)

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-client#226]
### Description
- Type: Bug

---------------------------------------------------------------
## Bug

**Version information**
(`mbed ls`)

```
mbed-os-example-client (f7ce74432bdd)
|- easy-connect (6fb5842becae)
|  |- atmel-rf-driver (57f22763f4d3)
|  |- esp8266-driver (4ed87bf7fe37)
|  |  `- ESP8266/ATParser (269f14532b98)
|  |- mcr20a-rf-driver (d8810e105d7d)
|  `- stm-spirit1-rf-driver (ac7a4f477222)
|- mbed-client (52e65b46dff7)
|  |- mbed-client-c (c739b8cbcc57)
|  |- mbed-client-classic (b9a521dcd0fc)
|  `- mbed-client-mbed-tls (7e1b6d815038)
|- mbed-os (f4864dc6429e)
`- pal (4e46c0ea8706)
```

**Expected Behavior**
Connection to mDC to work fine when using default (TCP) and Wifi connection on NUCLEO_L476RG

**Actual Behavior**
Unable to connect / register objects

**Steps to Reproduce**

Test results on multiple boards/configs.

- mbed-os-example-wifi
0b0f859c563bba23bef9591ddcb0711834026157
NUCLEO_L476RG + ESP8266 = works fine (list of SSID and connection successful)

- mbed-os-example-tls/client-tls
68d4005e3e8f768ed2f5fa303b0ea98590c16d3e
NUCLEO_L476RG + ESP8266 = works fine (TLS/TCP connection successful)

- mbed-os-example-client
f7ce74432bdd5759dcd28fcb9633e4f35c732490
K64F + ESP8266 = works fine (connection to mDC successful)

- mbed-os-example-client (UDP config)
mbed_app.json config: ` "NUCLEO_L476RG": {, "wifi-tx": "D8", "wifi-rx": "D2" } `
Removed LWIP as described here: https://github.com/ARMmbed/mbed-os-example-client/pull/225
NUCLEO_L476RG + ESP8266 = works fine (connection to mDC successful)

Logs:
```
Starting mbed Client example in IPv4 mode
[EasyConnect] Using WiFi (ESP8266) 
[EasyConnect] Connecting to WiFi mbed
[EasyConnect] Connected to Network successfully
[EasyConnect] IP address 10.0.0.33
[EasyConnect] MAC address 18:fe:34:dc:86:5c

SOCKET_MODE : UDP
Connecting to coap://api.connector.mbed.com:5684

Registered object successfully!
```

- mbed-os-example-client (TCP - default when using Wifi)
mbed_app.json config: ` "NUCLEO_L476RG": {, "wifi-tx": "D8", "wifi-rx": "D2" } `
Removed LWIP as described here: https://github.com/ARMmbed/mbed-os-example-client/pull/225
NUCLEO_L476RG + ESP8266 = Unable to connect:

Logs:
```
Starting mbed Client example in IPv4 mode
[EasyConnect] Using WiFi (ESP8266)
[EasyConnect] Connecting to WiFi mbed
[EasyConnect] Connected to Network successfully
[EasyConnect] IP address 10.0.0.33
[EasyConnect] MAC address 18:fe:34:dc:86:5c

SOCKET_MODE : TCP
Connecting to coap://api.connector.mbed.com:5684
simulate button_click, device not registered
simulate button_click, device not registered
....
[never registers in mDC]
```

Logs with trace enabled

```
[DBG ][mClt]: M2MConnectionHandlerPimpl::dns_hanG ][mClt]: M2MConnectionHandlerPimpl::dns_handler - _sodler - _socket_state = 0.[0m
[DBG ][mClt]: close_socket() - IN.[0m
[DBG ][mClt]: close_socket() - status: 0 OUT.[0m
[DBG ][mClt]: IP Address a9:2d:52:12.[0m
[DBG ][mClt]: init_socket - IN.[0m
[DBG ][mClt]: Interface count: 1.[0m
[DBG ][mClt]: Interface name: .[0m
[DBG ][mClt]: Interface no: 0.[0m
[DBG ][mClt]: init_socket - port 0.[0m
[DBG ][mClt]: init_socket - OUT.[0m
[DBG ][mClt]: resolve_server_address - Using TCP.[0m
[DBG ][mClt]: send_receive_event : _socket_state: ESocketStateConnectBeingCalled, ignoring event.[0m
[hangs here]
```

Investigated issue with @adustm 

@yogpan01 @JanneKiiskila  any thoughts on this?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1635

**Comment by anttiylitokola** [comment]
Will close this now. Let's follow this in ESP driver repo https://github.com/ARMmbed/esp8266-driver/issues/28
