### ISSUE TITLE
Border router dropping routes

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/mbed-os-example-client#232]
Using the latest GW_Binary image for Thread, I am observing the gateway becoming non-functional after a while, and starting to emit the following when trying to access a public IP from a node:
```[DBG ][ipv6]: XXX ipv6_buffer_route no route to {prefix}::68c7:55d3!```
and when trying to ping the node:
```
[DBG ][icmp]: Build NA
[DBG ][ipv6]: XXX ipv6_buffer_route no route to {prefix}:cae0:ebff:fe15:3829!
[WARN][ipv6]: ipv6_down route fail
```

Since it successfully routes the echo request from ethernet to Thread and to the node, but fails to route the echo response from the Thread network over to Ethernet, I think this is possibly some sort of corruption of the mesh -> LAN routing table?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1691

**Comment by yogpan01** [comment]
@artokin @mikter Can you please check this issue ?

**Comment by artokin** [comment]
Hi @stevew817 ,

Thanks for reporting this error. Would you please provide more details on this issue so that we can try to reproduce the error? 
* What and how many devices were attached to the network?
* How long did it take to get border router to the unresponsive state?
* What kind of traffic was made on network during operation (heavy load?, big packets?)

BR
Arto

**Comment by stevew817** [comment]
@artokin 

- 1 device attached to the border router, running mbed master
- Around 10 minutes after resetting the border router and end node
- Sending a ~190 byte CoAP payload every ~4 seconds. If it matters, this is to a NAT64 address, using the standard prefix 64:ff9b::

**Comment by artokin** [comment]
Thanks, we'll try to reproduce this issue.

**Comment by kjbracey-arm** [comment]
Was destination prefix was distinct from the Thread and Ethernet prefixes?

Presumably the border router received a default route from Ethernet via Router Advertisement at start-up? Has that timed out? I believe there should have been debug prints from both its addition and any timeout.

**Comment by stevew817** [comment]
@kjbracey-arm yes, external destination prefix is the NAT64 prefix (64:ff9b::/96). Trying to ping the node, the prefix was the Ethernet prefix, though.

Thanks for the suggestion. Out of precaution, I updated my router firmware, to see whether it could be the router that is messing up its RAs. We'll see whether that helps.

**Comment by TuomoHautamaki** [comment]
@stevew817 any update on this, did router firmware update help?

**Comment by stevew817** [comment]
I've been traveling, so haven't been able to get back to this yet. Will be back in the office next week.

**Comment by mikter** [comment]
@stevew817 can you give update on this issue please?

**Comment by stevew817** [comment]
As far as I can tell, a combination of updating the router and moving to a more stable tunnel provider helped. Sorry for raising the alarm!
