### ISSUE TITLE
Compilation fails with eth_v4 json

### ISSUE THREAD

**Issue by ranshe** [ARMmbed/mbed-os-example-client#233]
When switching from provided mbed_app.json to eth_v4.json, compilation fails with
"Compile [  0.2%]: NanostackRfPhyAtmel.cpp
[Fatal Error] NanostackRfPhyAtmel.cpp@18,44: nanostack/platform/arm_hal_phy.h: No such file or directory
[ERROR] .\easy-connect\atmel-rf-driver\source\NanostackRfPhyAtmel.cpp:18:44: fatal error: nanostack/platform/arm_hal_phy.h: No such file or directory
 #include "nanostack/platform/arm_hal_phy.h""

Please note that if your issue is reproducible on a specific configuration only,
it's likely an mbed-OS issue rather than mbed-os-example-client issue. We recommend
reporting the the issue then directly to 
[mbed-os reposititory](https://github.com/ARMmbed/mbed-os/issues) - please also
try searching for duplicates before filing a new one.

### Description
- Type: Bug | Enhancement | Question
- Related Issue: `#abc`

---------------------------------------------------------------
## Bug

**Version information**
(workspace) C:\Users\ranshe01\mbed-os-example-client>mbed ls
mbed-os-example-client (629b972f4110)
|- easy-connect (6fb5842becae)
|  |- atmel-rf-driver (57f22763f4d3)
|  |- esp8266-driver (4ed87bf7fe37)
|  |  `- ESP8266\ATParser (269f14532b98)
|  |- mcr20a-rf-driver (d8810e105d7d)
|  `- stm-spirit1-rf-driver (ac7a4f477222)
|- mbed-client (f8f0fc8b9321)
|  |- mbed-client-c (c739b8cbcc57)
|  |- mbed-client-classic (f673b8b60779)
|  `- mbed-client-mbed-tls (7e1b6d815038)
|- mbed-os (42be5c01a7f9)
`- pal (4e46c0ea8706)

**Environment details**
mbed compile -t GCC_ARM -m NUCLEO_F429ZI -c

**Expected Behavior**
compilation to work

**Actual Behavior**
compilation breaks

**Steps to Reproduce**
from mbed CLI on Windows:
mbed import mbed-os-example-client
cd mbed-os-example-client
generate new security.h file
copy configs\eth_v4.json to become mbed_app.json
compile as above

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1690

**Comment by ranshe** [comment]
Can be closed as duplicate of https://github.com/ARMmbed/mbed-os-example-client/issues/174.
A solution is to use following line in mbed_app.json:
"target.features_add": ["LWIP", "NANOSTACK", "COMMON_PAL"],
(adding NANOSTACK is key here)
