### ISSUE TITLE
Add an example of how to collect time series data from connector.mbed.com using Telegraf or Prometheus

### ISSUE THREAD

**Issue by amq** [ARMmbed/mbed-os-example-client#274]
### Description
- Type: Question

---------------------------------------------------------------

## Question

mbed Device Connector doesn't provide persistence, so an external metric-collecting tool is needed. You already have examples for AWS IoT, Azure IoTHub and others. I'd suggest creating one more example which would include an open-source self-hosted solution like Telegraf or Prometheus.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1865

**Comment by yogpan01** [comment]
Hi @amq , is this a requirement that you would like to see on the Server side , if yes, then @szysas can you please check this request ?

**Comment by amq** [comment]
@yogpan01 in other words, I'm looking for a way to collect and store the time series data from the mbed connector using an open-source tool.

**Comment by amq** [comment]
ie, extend https://github.com/ARMmbed/time_series_database_doc with an open-source solution in addition to Amazon and Azure.

**Comment by JanneKiiskila** [comment]
@MarceloSalazar  @senthilr - something you could be looking at?

**Comment by teetak01** [comment]
This issue really has nothing to do with Client-side functionality. I will close this.
