### ISSUE TITLE
Export test for make_armc5 mbed-os-5.6-oob2 (2nd round OOB) - K64F + Ethernet

### ISSUE THREAD

**Issue by vijhar01** [ARMmbed/mbed-os-example-client#314]
Note: This is just a template, so feel free to use/remove the unnecessary things

Please note that if your issue is reproducible on a specific configuration only,
it's likely an mbed-OS issue rather than mbed-os-example-client issue. We recommend
reporting the the issue then directly to 
[mbed-os reposititory](https://github.com/ARMmbed/mbed-os/issues) - please also
try searching for duplicates before filing a new one.

### Description
- Type: Bug

---------------------------------------------------------------
## Bug

**Version information**
(`mbed ls`)

**Environment details**
Windows 10
PS C:\mbed-os-example-client\configs> mbed config --list
[mbed] Global config:
ARM_PATH=C:\Keil_v5\ARM\ARMCC
IAR_PATH=C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.0\arm

[mbed] Local config (C:\mbed-os-example-client):
No local configuration is set

PS C:\mbed-os-example-client> mbed detect

[mbed] Detected K64F, port COM5, mounted D:
[mbed] Supported toolchains for K64F
+--------+-----------+-----------+-----------+-----------+-----------+-----------+
| Target | mbed OS 2 | mbed OS 5 |    ARM    |  GCC_ARM  |    IAR    |   ARMC6   |
+--------+-----------+-----------+-----------+-----------+-----------+-----------+
| K64F   | Supported | Supported | Supported | Supported | Supported | Supported |
+--------+-----------+-----------+-----------+-----------+-----------+-----------+
Supported targets: 1
Supported toolchains: 4

**Steps to Reproduce**

PS C:\mbed-os-example-client> mbed export -i make_armc5 -m K64F
Scan: .
Scan: FEATURE_LWIP
Scan: FEATURE_COMMON_PAL
Scan: FEATURE_STORAGE
PS C:\mbed-os-example-client> make
C:/mbed-os-example-client/makefile:966: warning: overriding commands for target `.s.o'
C:/mbed-os-example-client/makefile:961: warning: ignoring old commands for target `.s.o'
"Compile: ATParser.cpp"
process_begin: CreateProcess(NULL, armcc -c --gnu -Otime --split_sections --apcs=interwork --brief_diagnostics --restrict --multib
yte_chars -O0 -g -DMBED_DEBUG -DMBED_TRAP_ERRORS_ENABLED=1 --cpu=Cortex-M4.fp --md --no_depend_system_headers --c99 -D__ASSERT_MSG
 --cpp --no_rtti --no_vla --cpp --no_rtti --no_vla -DTARGET_KSDK2_MCUS -DFEATURE_LWIP=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_P
RESENT=1 -DTARGET_Freescale -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_LOWPOWERTIMER=1 -DDEVICE_RTC=1 -DTOOLCHAIN_object -D
DEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DFSL_RTOS_MBED -DDEVICE_STORAGE=1 -DTARGET_KPSDK_MCUS -DTARGET_CORTEX_M -DTARGET_DEBUG -DTA
RGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_UVISOR_UNSUPPORTED -DARM_MATH_CM4 -DTARGET_K64F -DDEVICE_SPI_ASYNCH=
1 -DDEVICE_PWMOUT=1 -DDEVICE_INTERRUPTIN=1 -DTARGET_CORTEX -DDEVICE_I2C=1 -DDEVICE_PORTOUT=1 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES
=1 -DCPU_MK64FN1M0VMD12 -DTARGET_LIKE_MBED -DFEATURE_COMMON_PAL=1 -DTARGET_KPSDK_CODE -DDEVICE_SERIAL_FC=1 -DFEATURE_STORAGE=1 -DD
EVICE_TRNG=1 -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DTARGET_FF_ARDUINO -DTARGET_FRDM -DTARGET_MCUXpresso_MCUS -DDEVICE_SPI=1 -DM
BED_BUILD_TIMESTAMP=1506346316.64 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DDEVICE_FLASH=1 -DDEVICE_PORTIN=1 -DT
OOLCHAIN_ARM -DTARGET_MCU_K64F -DTOOLCHAIN_ARM_STD --preinclude=mbed_config.h -I../ -I../. -I.././GW_Binary -I.././configs -I.././
docs -I.././docs/img -I.././easy-connect -I.././easy-connect/esp8266-driver -I.././easy-connect/esp8266-driver/ESP8266 -I.././easy
-connect/esp8266-driver/ESP8266/ATParser -I.././easy-connect/esp8266-driver/ESP8266/ATParser/BufferedSerial -I.././easy-connect/es
p8266-driver/ESP8266/ATParser/BufferedSerial/Buffer -I.././mbed-client -I.././mbed-client/mbed-client -I.././mbed-client/mbed-clie
nt-c -I.././mbed-client/mbed-client-c/doxygen -I.././mbed-client/mbed-client-c/nsdl-c -I.././mbed-client/mbed-client-c/source -I..
/./mbed-client/mbed-client-c/source/include -I.././mbed-client/mbed-client-classic -I.././mbed-client/mbed-client-classic/mbed-cli
ent-classic -I.././mbed-client/mbed-client-classic/source -I.././mbed-client/mbed-client-mbed-tls -I.././mbed-client/mbed-client-m
bed-tls/mbed-client-mbedtls -I.././mbed-client/mbed-client-mbed-tls/source -I.././mbed-client/source -I.././mbed-client/source/inc
lude -I.././mbed-os -I.././mbed-os/cmsis -I.././mbed-os/cmsis/TARGET_CORTEX_M -I.././mbed-os/cmsis/TARGET_CORTEX_M/TOOLCHAIN_ARM -
I.././mbed-os/drivers -I.././mbed-os/events -I.././mbed-os/events/equeue -I.././mbed-os/features -I.././mbed-os/features/FEATURE_C
OMMON_PAL -I.././mbed-os/features/FEATURE_COMMON_PAL/mbed-client-randlib -I.././mbed-os/features/FEATURE_COMMON_PAL/mbed-client-ra
ndlib/mbed-client-randlib -I.././mbed-os/features/FEATURE_COMMON_PAL/mbed-client-randlib/mbed-client-randlib/platform -I.././mbed-
os/features/FEATURE_COMMON_PAL/mbed-client-randlib/source -I.././mbed-os/features/FEATURE_COMMON_PAL/mbed-coap -I.././mbed-os/feat
ures/FEATURE_COMMON_PAL/mbed-coap/doxygen -I.././mbed-os/features/FEATURE_COMMON_PAL/mbed-coap/mbed-coap -I.././mbed-os/features/F
EATURE_COMMON_PAL/mbed-coap/source -I.././mbed-os/features/FEATURE_COMMON_PAL/mbed-coap/source/include -I.././mbed-os/features/FEA
TURE_COMMON_PAL/mbed-trace -I.././mbed-os/features/FEATURE_COMMON_PAL/mbed-trace/mbed-trace -I.././mbed-os/features/FEATURE_COMMON
_PAL/mbed-trace/source -I.././mbed-os/features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos -I.././mbed-os/features/FEATURE_CO
MMON_PAL/nanostack-hal-mbed-cmsis-rtos/cs_nvm -I.././mbed-os/features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/nvm -I.././
mbed-os/features/FEATURE_COMMON_PAL/nanostack-libservice -I.././mbed-os/features/FEATURE_COMMON_PAL/nanostack-libservice/mbed-clie
nt-libservice -I.././mbed-os/features/FEATURE_COMMON_PAL/nanostack-libservice/mbed-client-libservice/platform -I.././mbed-os/featu
res/FEATURE_COMMON_PAL/nanostack-libservice/source -I.././mbed-os/features/FEATURE_COMMON_PAL/nanostack-libservice/source/IPv6_fcf
_lib -I.././mbed-os/features/FEATURE_COMMON_PAL/nanostack-libservice/source/libBits -I.././mbed-os/features/FEATURE_COMMON_PAL/nan
ostack-libservice/source/libList -I.././mbed-os/features/FEATURE_COMMON_PAL/nanostack-libservice/source/libTrace -I.././mbed-os/fe
atures/FEATURE_COMMON_PAL/nanostack-libservice/source/libTrace/scripts -I.././mbed-os/features/FEATURE_COMMON_PAL/nanostack-libser
vice/source/libip6string -I.././mbed-os/features/FEATURE_COMMON_PAL/nanostack-libservice/source/nsdynmemLIB -I.././mbed-os/feature
s/FEATURE_COMMON_PAL/nanostack-libservice/source/nvmHelper -I.././mbed-os/features/FEATURE_COMMON_PAL/sal-stack-nanostack-eventloo
p -I.././mbed-os/features/FEATURE_COMMON_PAL/sal-stack-nanostack-eventloop/nanostack-event-loop -I.././mbed-os/features/FEATURE_CO
MMON_PAL/sal-stack-nanostack-eventloop/nanostack-event-loop/platform -I.././mbed-os/features/FEATURE_COMMON_PAL/sal-stack-nanostac
k-eventloop/source -I.././mbed-os/features/FEATURE_LWIP -I.././mbed-os/features/FEATURE_LWIP/lwip-interface -I.././mbed-os/feature
s/FEATURE_LWIP/lwip-interface/lwip -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-eth -I.././mbed-os/features/FEATURE_LW
IP/lwip-interface/lwip-eth/arch -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_Freescale -I.././mbed-os/
features/FEATURE_LWIP/lwip-interface/lwip-sys -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch -I.././mbed-os/fea
tures/FEATURE_LWIP/lwip-interface/lwip/src -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/api -I.././mbed-os/feature
s/FEATURE_LWIP/lwip-interface/lwip/src/core -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4 -I.././mbed-os/
features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6 -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include -I../
./mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/
include/lwip/priv -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot -I.././mbed-os/features/FEATURE_L
WIP/lwip-interface/lwip/src/include/netif -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp -I.././mb
ed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/polarssl -I.././mbed-os/features/FEATURE_LWIP/lwip-interface
/lwip/src/netif -I.././mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp -I.././mbed-os/features/FEATURE_LWIP/lwip-i
nterface/lwip/src/netif/ppp/polarssl -I.././mbed-os/features/filesystem -I.././mbed-os/features/filesystem/bd -I.././mbed-os/featu
res/filesystem/fat -I.././mbed-os/features/filesystem/fat/ChaN -I.././mbed-os/features/frameworks -I.././mbed-os/features/framewor
ks/greentea-client -I.././mbed-os/features/frameworks/greentea-client/greentea-client -I.././mbed-os/features/frameworks/greentea-
client/source -I.././mbed-os/features/frameworks/unity -I.././mbed-os/features/frameworks/unity/source -I.././mbed-os/features/fra
meworks/unity/unity -I.././mbed-os/features/frameworks/utest -I.././mbed-os/features/frameworks/utest/source -I.././mbed-os/featur
es/frameworks/utest/utest -I.././mbed-os/features/mbedtls -I.././mbed-os/features/mbedtls/importer -I.././mbed-os/features/mbedtls
/inc -I.././mbed-os/features/mbedtls/inc/mbedtls -I.././mbed-os/features/mbedtls/platform -I.././mbed-os/features/mbedtls/platform
/inc -I.././mbed-os/features/mbedtls/platform/src -I.././mbed-os/features/mbedtls/src -I.././mbed-os/features/mbedtls/targets -I..
/./mbed-os/features/nanostack -I.././mbed-os/features/netsocket -I.././mbed-os/features/netsocket/cellular -I.././mbed-os/features
/netsocket/cellular/generic_modem_driver -I.././mbed-os/features/netsocket/cellular/utils -I.././mbed-os/features/storage -I.././m
bed-os/features/storage/FEATURE_STORAGE -I.././mbed-os/features/storage/FEATURE_STORAGE/cfstore -I.././mbed-os/features/storage/FE
ATURE_STORAGE/cfstore/configuration-store -I.././mbed-os/features/storage/FEATURE_STORAGE/cfstore/doc -I.././mbed-os/features/stor
age/FEATURE_STORAGE/cfstore/doc/design -I.././mbed-os/features/storage/FEATURE_STORAGE/cfstore/doc/design/pics -I.././mbed-os/feat
ures/storage/FEATURE_STORAGE/cfstore/doc/design/umlet -I.././mbed-os/features/storage/FEATURE_STORAGE/cfstore/doc/project -I.././m
bed-os/features/storage/FEATURE_STORAGE/cfstore/source -I.././mbed-os/features/storage/FEATURE_STORAGE/flash-journal -I.././mbed-o
s/features/storage/FEATURE_STORAGE/flash-journal/flash-journal-strategy-sequential -I.././mbed-os/features/storage/FEATURE_STORAGE
/storage-volume-manager -I.././mbed-os/features/storage/FEATURE_STORAGE/storage-volume-manager/source -I.././mbed-os/features/stor
age/FEATURE_STORAGE/storage-volume-manager/storage-volume-manager -I.././mbed-os/hal -I.././mbed-os/hal/storage_abstraction -I../.
/mbed-os/platform -I.././mbed-os/rtos -I.././mbed-os/rtos/TARGET_CORTEX -I.././mbed-os/rtos/TARGET_CORTEX/rtx4 -I.././mbed-os/rtos
/TARGET_CORTEX/rtx5 -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/TARGET_RTOS_M4_M7 -I.././mbed-os/rtos/TARGET_CORTEX/rtx5/TARGET_RTOS_M4
_M7/TOOLCHAIN_ARM -I.././mbed-os/targets -I.././mbed-os/targets/TARGET_Freescale -I.././mbed-os/targets/TARGET_Freescale/TARGET_MC
UXpresso_MCUS -I.././mbed-os/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F -I.././mbed-os/targets/TARGET_Freesca
le/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM -I.././mbed-os/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K6
4F/device -I.././mbed-os/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_ARM_STD -I.././mbed-os/t
argets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers -I.././mbed-os/targets/TARGET_Freescale/TARGET_MCUXpresso_M
CUS/api -I.././pal -I.././pal/Source -I.././pal/Source/PAL-Impl -I.././pal/Source/PAL-Impl/Modules -I.././pal/Source/PAL-Impl/Modu
les/Networking -I.././pal/Source/PAL-Impl/Modules/RTOS -I.././pal/Source/PAL-Impl/Modules/Update -I.././pal/Source/PAL-Impl/Servic
es-API -I.././pal/Source/Port -I.././pal/Source/Port/Platform-API -I.././pal/Source/Port/Reference-Impl -I.././pal/Source/Port/Ref
erence-Impl/mbedOS -I.././pal/Source/Port/Reference-Impl/mbedOS/Networking -I.././pal/Source/Port/Reference-Impl/mbedOS/RTOS -o ea
sy-connect/esp8266-driver/ESP8266/ATParser/ATParser.o ../easy-connect/esp8266-driver/ESP8266/ATParser/ATParser.cpp, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [easy-connect/esp8266-driver/ESP8266/ATParser/ATParser.o] Error 2
make: *** [all] Error 2
PS C:\mbed-os-example-client>
----------------------------------------------------------------

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2009

**Comment by anttiylitokola** [comment]
Please open this on mbed-os side. This is not a mbed-client issue. FYI @MarceloSalazar
