### ISSUE TITLE
Wifi ST idw0x using NULL_ENTROPY

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-client#353]
The ST Wifi configuration for idw01 and idw04 are using:
- MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES
- MBEDTLS_TEST_NULL_ENTROPY

See json configuration:
- https://github.com/ARMmbed/mbed-os-example-client/blob/master/configs/wifi_idw01m1_v4.json#L24
- https://github.com/ARMmbed/mbed-os-example-client/blob/master/configs/wifi_idw04a1_v4.json#L24

This is not compliant with the level of security we are requesting.
Therefore, need to make this work with TLS / entropy, or remove the configurations and documentation that are claiming this Wifi shields/drivers to be supported.

@betzw

cc @JanneKiiskila @screamerbg @ashok-rao

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2271

**Comment by betzw** [comment]
Well, it are not the WiFi shields which are not supporting TLS/entropy but the NUCLEO base board(s) (e.g. `NUCLEO_F401RE`) which I use for testing that do not support this security level.

**Comment by MarceloSalazar** [comment]
Perhaps we can switch to `NUCLEO_L4x6RG`?
I don't think `NUCLEO_F401RE` meets the requirements and should be dropped from this example app.

**Comment by JanneKiiskila** [comment]
That sounds like the right conclusion. Which other base board would do?

**Comment by JanneKiiskila** [comment]
(Or implement the entropy parts to that board as well, that's another way out of it).

**Comment by JanneKiiskila** [comment]
There's a test matrix; https://os.mbed.com/teams/ST/wiki/Matrix-of-tested-boards
I think we could pick up another board from there?  NUCLEO L476RG potentially?

**Comment by betzw** [comment]
> The ST Wifi configuration for idw01 and idw04 are using:
>
>   - MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES
>   - MBEDTLS_TEST_NULL_ENTROPY

Would it help if we remove those `macros` sections of
- [`configs/wifi_idw01m1_v4.json`](https://github.com/ARMmbed/mbed-os-example-client/blob/master/configs/wifi_idw01m1_v4.json#L24), and
- [`configs/wifi_idw04a1_v4.json`](https://github.com/ARMmbed/mbed-os-example-client/blob/master/configs/wifi_idw04a1_v4.json#L24)

?!?

**Comment by JanneKiiskila** [comment]
It will compile then at all, I'm afraid.

```
[Error] config.h@2743,2: #error "No entropy source was found at build time, so TLS " "functionality is not available"
[ERROR] In file included from ./mbed-client/mbed-client-mbed-tls/mbed-client-mbedtls/m2mconnectionsecuritypimpl.h:25:0,
                 from ./mbed-client/mbed-client-mbed-tls/source/m2mconnectionsecurity.cpp:22:
./mbed-os/features/mbedtls/inc/mbedtls/config.h:2743:2: error: #error "No entropy source was found at build time, so TLS " "functionality is not available"
 #error "No entropy source was found at build time, so TLS " \
```

**Comment by betzw** [comment]
Which base board are you using?

**Comment by JanneKiiskila** [comment]
This compilation with with using the `configs/wifi_idw01m1_v4.json` and just `mbed compile -m NUCLEO_F401RE -t GCC_ARM`.

**Comment by betzw** [comment]
Well, the `NUCLEO_F401RE` does not provide support for `TLS/entropy` and such the compilation correctly produces the above errors.
You might want to try to compile for base boards which support TLS, e.g. NUCLEO boards `NUCLEO_L4x6RG`.

**Comment by betzw** [comment]
@MarceloSalazar, @JanneKiiskila 
Can we close this issue?

**Comment by JanneKiiskila** [comment]
Yep!
