### ISSUE TITLE
When device connect to mbed cloud, It prints "device not registerd" message.

### ISSUE THREAD

**Issue by kaizen8501** [ARMmbed/mbed-os-example-client#366]
### Description
- Type: Question

Version Information(mbed ls)
F:\GitHub_Repository\ARM\mbed-os-example-client>mbed ls
mbed-os-example-client (33ae628ef1c5)
|- easy-connect (00f21d0ae5bf)
|  |- atmel-rf-driver (2cd9abba3e37)
|  |- esp8266-driver (b0d79dad507d)
|  |- mcr20a-rf-driver (9aac10474702)
|  |- stm-spirit1-rf-driver (0ff4ca7537f0)
|  |- wifi-x-nucleo-idw01m1 (537b01c4a053)
|  `- wizfi310-driver (aa69a975673a)
|- mbed-client (ea04c5de7822)
|  |- mbed-client-c (ecfa619e42b2)
|  |- mbed-client-classic (4e66929607c3)
|  `- mbed-client-mbed-tls (7e1b6d815038)
|- mbed-os (2b4ff78ab0a5)
`- pal (60ce64d5ec35)

Environment details
Hw:
client : K64F + WizFi310( Wiznet Wi-Fi Shield ) ( https://os.mbed.com/components/WizFi310-EVB/ )

Expected Behavior
registered object successfully

## Question

Hi~ I'm Patrick at WIZnet
I modified "easy-connect" for using our Wi-Fi module(WizFi310) with mbed cloud.
But I have a problem when connect to "mbed cloud server" using our Wi-Fi module.

This is our log message when problem is occurred.

![04_log](https://user-images.githubusercontent.com/3273287/34508928-42f67882-f088-11e7-91ac-77aa542f079a.png)

My analysis result, It continually fail while SSL handshake with mbed cloud. I think SSL handshake is done but cloud server send reject packet to our device.

I attached packet capture file for WireShark. If you need more detailed information, refer to this file.

In this picture, 78 line is error packet from mbed cloud. Detailed information of this packet is as below.
![05_log](https://user-images.githubusercontent.com/3273287/34509031-e6e9cb7e-f088-11e7-87f0-cbc07f8908d9.png)

![06_log](https://user-images.githubusercontent.com/3273287/34509074-3648b644-f089-11e7-91f1-0297de17b9a7.png)

For packet capture file, refer to this URL.

[WizFi310 Fail mbed cloud.zip](https://github.com/ARMmbed/mbed-os-example-client/files/1599406/WizFi310.Fail.mbed.cloud.zip)

I need your help or guide to solve this problem.

Thank you.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2293

**Comment by kaizen8501** [comment]
I solved this problem. In this problem, my device didn't send certificate packet that is reason.
