### ISSUE TITLE
A client example failed when proper entropy collector has not been implemented

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/mbed-os-example-client#39]
In K64F platform, the macro ```MBEDTLS_ENTROPY_HARDWARE_ALT``` is defined in the ```target.json``` and proper implementation has been done in the HAL.

https://github.com/mbedmicro/mbed/pull/1879

Some platforms do not support RNG hardware and expect to use software solution. e.g. build client example without ```MBEDTLS_ENTROPY_HARDWARE_ALT``` macro.

In that case, I got connection error below if I removed the ```MBEDTLS_ENTROPY_HARDWARE_ALT``` macro in K64F platform (as non RNG support device).

```
Starting mbed Client example...
Using Ethernet

Connected to Network successfully
IP address 10.128.4.32

SOCKET_MODE : UDP
Connecting to coap://api.connector.mbed.com:5684

[ERROR:] M2MInterface::SecureConnectionFailed
```
Attached files is mbed-trace log: [trace_log_failed.txt](https://github.com/ARMmbed/mbed-os-example-client/files/363380/trace_log_failed.txt)

So, my question is:

* Is the ```MBEDTLS_ENTROPY_HARDWARE_ALT``` macro and entropy collector implementation mandatory feature, or optional?

If this is optional, the ```nanostack-hal-mbed-cmsis-rtos``` should also have software implementation and the client example should not fail.

https://github.com/ARMmbed/nanostack-hal-mbed-cmsis-rtos/blob/master/arm_hal_random.c#L28

**Comment by yogpan01** [comment]
Closing this issue as it is now solved by providing the work around for different hardware boards.
