### ISSUE TITLE
[multiple targets] Unable to connect using Wifi 

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-client#54]
Tested RC4 and commented out SW2 / SW3
GCC, Windows

Targets:
- NUCLEO_F401RE, F411RE: No error message on serial port
- NUCLEO_F746ZG: `[ERROR:] M2MInterface::SecureConnectionFailed`

Targets not expected to work
- DISCO_F429ZI - No arduino headers available
- RZ_A1H - Wifi module doesn't fit well

**Comment by yogpan01** [comment]
Closing this issue as it is now solved.
