### ISSUE TITLE
[Uvision export] Error in SVC_Table.S

### ISSUE THREAD

**Issue by sarahmarshy** [ARMmbed/mbed-os-example-client#61]
This is the exact error when building in uvision after calling the mbed export command for K64F:
```
SVC_Table.S: error: A3907U: Via file '.\.build\uvision5\svc_table._ia' command too long for buffer.
```

**Comment by 0xc0170** [comment]
Please check if this is logged already in mbed repository, as it's related to its flags, not this repository (it's good that we got an example how to reproduce a problem).

**Comment by sarahmarshy** [comment]
@0xc0170. It is solved in mbed now with  https://github.com/ARMmbed/mbed-os/pull/2377
