### ISSUE TITLE
[IAR export] Multiple tools write to the same file.

### ISSUE THREAD

**Issue by sarahmarshy** [ARMmbed/mbed-os-example-client#62]
This is the exact error when building in IAR after calling the mbed export command for K64F:
```
Build error: Multiple tools write to the same file.
  File: C:\Repos\oob\mbed-os-example-client\projectfiles\iar_K64F\.build\iar_arm\Obj\Timeout.o 
  Tool 1: C/C++ Compiler, when processing C:\Repos\oob\mbed-os-example-client\mbed-os\features\FEATURE_COMMON_PAL\sal-stack-nanostack-eventloop\bare-metal\timeout.c 
  Tool 2: C/C++ Compiler, when processing C:\Repos\oob\mbed-os-example-client\mbed-os\hal\common\Timeout.cpp 



```

**Comment by 0xc0170** [comment]
I recall I created an issue for this but probably in the repo that was private. This is known limitation of some tools, like IAR that does not like having 2 objects files with the same name. Please create an issue in mbed repo, as both files are part of it. We will need to figure out how to fix this, I suspect  this is not just a case of IAR but other tools as well.

**Comment by yogpan01** [comment]
Is this issue now created on mbed OS ? 
@sarahmarshy Please create log this issue on mbed OS and close it from here.

**Comment by sarahmarshy** [comment]
https://github.com/ARMmbed/mbed-os/issues/2344
