### ISSUE TITLE
Thread connection failure with mcr20a-rf-driver

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-os-example-client#65]
K64F + MCR20A shield
GCC_ARM & IAR compilers 
MESH_THREAD configuration
Channel 12
connecting to mbed border router with thread dynamic binary image

6lowpan works, but thread fails.

mbed-os-example-client (514b735fd3d
|- esp8266-driver (450cc128865f)
|- mbed-os (4b506280eb4d)
`- mcr20a-rf-driver (70ce90214856)

Logs attached
[thread_rc4_mcr20a_gcc.txt](https://github.com/ARMmbed/mbed-os-example-client/files/398026/thread_rc4_mcr20a_gcc.txt)
[thread_rc4_mcr20a_iar.txt](https://github.com/ARMmbed/mbed-os-example-client/files/398030/thread_rc4_mcr20a_iar.txt)

**Comment by yogpan01** [comment]
@hasnainvirk Can this issue be closed now ? If yes, please close it.

**Comment by hasnainvirk** [comment]
Positive. This should be closed. @maclobdell can you please close this ?

**Comment by maclobdell** [comment]
Let me test this again just to confirm.

**Comment by maclobdell** [comment]
There is still an issue connecting to a thread network with this example and mcr20a rf shield and driver.  I tested this twice with slightly different results each time.  Attached are the two logs.  This exact setup works fine with atmel shield and rf driver.  I waited 5+ minutes between all tests.    

[mbed-os-example-client-5.1.0-mcr20a_test_log_2.txt](https://github.com/ARMmbed/mbed-os-example-client/files/409633/mbed-os-example-client-5.1.0-mcr20a_test_log_2.txt)

[mbed-os-example-client-5.1.0-mcr20a_test_log.txt](https://github.com/ARMmbed/mbed-os-example-client/files/409593/mbed-os-example-client-5.1.0-mcr20a_test_log.txt)

Logs say No IP Address.  Later it shows other failing attempts.

mbed-os-5.1.0 tag
K64F + MCR20A shield
GCC_ARM compiler 
MESH_THREAD configuration
Channel 12
connecting to mbed border router with thread dynamic binary image


mbed-os-example-client (2b5ecfb5f770
|- esp8266-driver (450cc128865f)
|- mbed-os (0712b8adf6bb)
`- mcr20a-rf-driver (70ce90214856)


MESH_LOWPAN_ND configuration works fine.  Just Thread fails consistently.

**Comment by hasnainvirk** [comment]
@maclobdell I will ask someone in cambridge to send me this rf shield. Without having hardware I can't help you no matter how much I want to do so.

**Comment by yogpan01** [comment]
@hasnainvirk @maclobdell Is this issue resolved ?

**Comment by hasnainvirk** [comment]
@yogpan01 I have the hardware now. But I had not have any time to look into it.

**Comment by hasnainvirk** [comment]
@yogpan01 @AnttiKauppila I am not able to Connect to Connector using Thread with any RF shield.
I tried with both atme-rf-shield and mcr20a-rf-shield.

-> Thread network gets established. 
-> Node gets the IP address (both with atmel-rf and mcr20a)
-> Then it tries to connect to Connector

Symptoms:

* I can only see Client Hello messages in Wireshark.
* No reponse from Connector.
* In Clinet Hello message I see a UDP Checksum Error (This might be a Wireshark bug on my end.)

However, the end result is that I am unable to connect to Connector.

**Comment by hasnainvirk** [comment]
@yogpan01 @AnttiKauppila @maclobdell 

Alright, it seems that the my 4G Elisa device (for backhaul connectivity) needed a firmware update. Its DHCPv6 mechanism was not working properly. So I was getting an IPv6 address but it wasn't routable at ISP's end. I updated the firmware and everything worked fine.

I tried with both atmel-rf-shield and mcr20a-rf-shield. Both worked fine.

I think this issue can be closed.

**Comment by TuomoHautamaki** [comment]
@yogpan01, @maclobdell please close this one unless you think this requires further studies. In our tests things worked fine

**Comment by yogpan01** [comment]
@maclobdell can you please close this issue ?

**Comment by maclobdell** [comment]
Looks like the issue could have been due to an unconnected antenna on my mcr20a shield.  Both 6lowpan and thread networking is passing now.  This can be closed.  Thanks.
