### ISSUE TITLE
Current checkout (001fe0d) Not running in K64F and NUCLEO_F401RE

### ISSUE THREAD

**Issue by javier-moreno-tridonic-com** [ARMmbed/mbed-os-example-client#69]
I using the following checkouts:
- **mbed-os-example-client** 001fe0d045d8b7b9675646ac5a58ae3a22469e22
- **mbed-os** dd36dc4228b52ae538ecaa2f1a1dbba9260b9bd9
- **esp8266-driver** 450cc128865ffb90b5cbfe5af193621644024fa7
- **atmel-rf-driver** a16a4ed6f6e8d5f2d009f25b6ab7c38affb5019c

The project builds fine, but when I try running it I never reaches main. 

Stack trace looks like this:

> mbed-os-example-client.elf	
> >Thread #1 <main> (Suspended : Signal : SIGTRAP:Trace/breakpoint trap)	
> >>__isr_vector() at 0x0	
> 0x0	

If I try to compile it with "MESH_LOWPAN_ND" as a network-interface I get:

>mbed-os-example-client.elf	
>>Thread #1 (Suspended : User Request)	
>>> __isr_vector() at 0x0	
>thread_comm_status_indication_cb() at 0xa400

**Comment by javier-moreno-tridonic-com** [comment]
I was compiling with GCC:
> arm-none-eabi-g++ (GNU Tools for ARM Embedded Processors) 4.9.3 20150303 (release) [ARM/embedded-4_9-branch revision 221220]
> arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150303 (release) [ARM/embedded-4_9-branch revision 221220]

Using:
> mbed compile -c -m NUCLEO_F401RE -t GCC_ARM
For the nucleo board and 
> mbed compile -c -m K64F -t GCC_ARM
For the freescale one

@hasnainvirk Sure we can set up a Skype session. Can you provide me with a contact mail to look for a suitable date?

**Comment by hasnainvirk** [comment]
@javier-moreno-tridonic-com , please contact me at hasnain.virk@arm.com
skype: husnain.virk

**Comment by javier-moreno-tridonic-com** [comment]
Hi there, looks like it was my compiler version. I tried again with a clean checkout of the example today and an updated compiler and it works for both targets. 

The versions I'm using now are:
> arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160609 (release) [ARM/embedded-5-branch revision 237715]

> arm-none-eabi-g++ (GNU Tools for ARM Embedded Processors) 5.4.1 20160609 (release) [ARM/embedded-5-branch revision 237715]

Thank you all for your hints and comments.

**Comment by yogpan01** [comment]
@javier-moreno-tridonic-com  
Hi,
According to the documentation mentioned here (https://docs.mbed.com/docs/mbed-os-handbook/en/5.1/dev_tools/cli/#installing-mbed-cli)

>  If you want to use the GCC ARM Embedded toolchain, set GCC_ARM_PATH to the binary directory of your GCC ARM installation (example: C:\Program Files\GNU Tools ARM Embedded\4.9 2015q2\bin). Use versions 4.9 of GCC ARM Embedded; version 5.0 or any version above might be incompatible with the tools.
> 

You may run into some unknown issues with latest compiler > 4.9

**Comment by hasnainvirk** [comment]
@javier-moreno-tridonic-com Mate I had been trying with 4.9. It was working perfectly. I think the culprit might have been some mishap during your last checkout. Something wasn't right. Please test latest checkout with 4.9, it should work.

**Comment by javier-moreno-tridonic-com** [comment]
Ok thanks for the heads up. I will try with a different 4.9 release (I was using q1 and the documentation suggests that q2 is used)
