### ISSUE TITLE
Can't register mbed-client object successfully through WiFi

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/mbed-os-example-client#75]
Based on the up-to-date version, I can't register mbed-client object successfully through WiFi on K64F.
However, it could work fine based on the old version download on 07/18.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-918

**Comment by yogpan01** [comment]
@geky Please check this.

**Comment by geky** [comment]
Looking into this more, but it looks like this issue only occurs when mbed-trace is enabled.

**Comment by maclobdell** [comment]
also looks like compiling with gcc_arm works, but with armcc compiler it does not.

**Comment by geky** [comment]
This requires more testing, but I believe https://github.com/ARMmbed/mbed-os/pull/2530 should solve this issue.
