### ISSUE TITLE
A binary built with ARMCC is not able to connect to the connector.

### ISSUE THREAD

**Issue by byungdoochoi** [ARMmbed/mbed-os-example-client#80]
**Step:**
1-1. Build this example with the online compilation environment.
1-2. Build this example with mbed cli with -t ARM.
2. Flash the binary and turn on the K64F and ESP8266.
3. See it connects to a wifi AP.

**Symptom:**
It can't connect to the connector; stops moving forward after this line:
-------
SOCKET_MODE : UDP
Connecting to coap://api.connector.mbed.com:5684
-------
Enabling logs from ESP8266Interface, I could see below is the last AT command:
-------
AT> AT+CIPSTART
-------

**Supposed to be:**
You should see "Registered object successfully!" from your terminal.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1007

**Comment by yogpan01** [comment]
@geky Please check this , it works for GCC but not for ARMCC

**Comment by janjongboom** [comment]
@yogpan01 @geky Same issue for me, also breaks Simple mbed Client. How can this not be a priority?

**Comment by yogpan01** [comment]
@janjongboom which ARMCC build are you using ?

**Comment by janjongboom** [comment]
@yogpan01 Online compiler. Load mbed-os-example-client in the online compiler, add security.h, compile -> does not do anything on my K64F...

**Comment by yogpan01** [comment]
Hi, there is a new release for mbed OS 5.2 and if there is still an issue with WiFi or some compile version, I suggest to open it up on mbed-os repository as that is the right place to handle such issues, mbed Client only uses those APIs just like any other application and if you are experiencing issues like non-connection on different compiles, it has to be raised on mbed-os.
