### ISSUE TITLE
Not able to set Nanostack_IPv6 for M2MInterfaceFactory::create_interface

### ISSUE THREAD

**Issue by ivan-adzic-tridonic-com** [ARMmbed/mbed-os-example-client#81]
It said, not supported... while in mbed3 we were able to use it. What that means and why only M2MInterface::LwIP_IPv4 is supported for the moment. 

"ConnectionHandler: Unsupported network stack, only IPv4 is currently supported"

@MarceloSalazar

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1030

**Comment by yogpan01** [comment]
Hi,
You need not set that interface anymore, you can leave it to be LwIP_IPv4 , and set the Nanostack Interface and pass it to set_platform_network_handler().
Just check the example implementation.
