### ISSUE TITLE
build failure with Nucleo boards

### ISSUE THREAD

**Issue by mridup** [ARMmbed/mbed-os-example-client#83]
compilation fails when built for Nucleo boards. Tried a build with K64F which builds OK.
Adding the ENTROPY macros in mbed_app.json does not add the macros to the mbed_config.h file in the .build/ folder.

`"macros": ["MBEDTLS_USER_CONFIG_FILE=\"mbedtls_mbed_client_config.h\"",
                "MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES",
                "MBEDTLS_TEST_NULL_ENTROPY"],`

In fact the first macro added is repeatedly added to the file multiple times.
E.g. in mbed_config.h (./build/NUCLEO_L476RG/GCC_ARM)
`
# define MBEDTLS_TEST_NULL_ENTROPY
# define MBEDTLS_TEST_NULL_ENTROPY
# define MBEDTLS_TEST_NULL_ENTROPY
# define MBEDTLS_TEST_NULL_ENTROPY

`

error is generated in the file mbed-os/features/mbedtls/inc/mbedtls/check_config.h line no.135
`#error "MBEDTLS_TEST_NULL_ENTROPY defined, but not all prerequisites"`

This failure happens both in mbed-cli and the online compiler.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1032

**Comment by yogpan01** [comment]
@mridup Can you please list your mbed-cli and mbed-os versions ?

**Comment by yogpan01** [comment]
The latest mbed-os and mbed-cli seems to have different behaviour with config json parameters, this needs to be moved to mbed-os team to verify and propose what has changed. Client can only change documentation when its sure how the mbed Configuration mechanism is working.
@bogdanm @0xc0170 @c1728p9 Please check this and propose what is the correct way to pass these parameters?

**Comment by yogpan01** [comment]
Please re-test this with latest mbed OS 5.2 and client example. However, it is strongly recommended NOT to disable security through this work-around.
Please check this https://github.com/ARMmbed/mbed-os-example-client#supported-target-hardware-configurations and also
https://github.com/ARMmbed/mbed-os-example-client#requirements-for-non-k64f-boards again

**Comment by yogpan01** [comment]
Hi, We are assuming that this is resolved for you, in case if it is still an issue please reopen this issue or open a new one.
