### ISSUE TITLE
problem for sending packet between SED and router

### ISSUE THREAD

**Issue by SYuPing** [ARMmbed/mbed-os-example-client#86]
Hi,

I set two endpoints(1 router, 1 sleepy end device) to connect to mDS within gateway, I want to let SED send a packet to router by thread in this example, is this possible and how do I do this?

Many thanks.

**Comment by yogpan01** [comment]
@artokin @mikter Can you please provide info for this query ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1039

**Comment by mikter** [comment]
This is not thread issue as thread only gives IP connectivity. 

@hasnainvirk can you help how to use socket API to send message to othre device in internet.

**Comment by SYuPing** [comment]
@mikter What you mean is I could use socket(e.x UDP) API content address which is IPv6 preifx + device EUI64 address to finish it?

**Comment by hasnainvirk** [comment]
@SYuPing I gave example code with instructions to Sam. Please contact him.

**Comment by SYuPing** [comment]
@hasnainvirk Thanks a lot, it is very useful for us.
This problem is gonna be solved and I close this issue.

Thanks.
