### ISSUE TITLE
Example is no longer working with 6LoWPAN

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/mbed-os-example-client#94]
When doing 'mbed add atmel-rf-driver', it adds the atmel-driver-rf repository on the master branch. It looks like there have been changes there that are not interoperable with the mbed client example causing the build to fail.

Either add a .lib pointing to the right commit to get this to work, or update the readme, please.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1079

**Comment by yogpan01** [comment]
@hasnainvirk @SeppoTakalo Please look into this .

**Comment by teetak01** [comment]
@stevew817 we have made numerous fixes to the example last week. Also the README has been updated. Your issue should be resolved now. Sorry for the delay.

**Comment by SeppoTakalo** [comment]
This should be closed as the original issue has been fixed.

**Comment by teetak01** [comment]
Hi @stevenewey I'll close this issue now. Please open a new ticket if you see new issues. Thank you for reporting.
